### ISSUE TITLE
Test physical UI, buzzer/vibration motor, component durability

### ISSUE THREAD

**Issue by thaeli** [AEFeinstein/Swadge-Devkit#22]
* Prototype some physical UI concepts (concept board shapes) and wire in buttons for basic usability testing

* Evaluate piezo buzzers and vibration motors for potential use instead of 4th button

* Potentially destructive testing (on spare parts, not the devkit!) - screen durability, screen behavior at low voltage, etc.

**Comment by AEFeinstein** [comment]
Piezo buzzers work fine. OLED durability is TBD (but hopefully resolved soon after we get test boards)

**Comment by AEFeinstein** [comment]
A secondary PCB bezel seems to provide the most protection and style. Adding components to the bezel will get costly.

**Comment by AEFeinstein** [comment]
Hagrid did the job, should be good to go
